export const sagaTypes = Object.freeze({
    FETCH_TASKS_REQUEST: 'FETCH_TASKS_REQUEST',
    FETCH_TASKS_SUCCESS: 'FETCH_TASKS_SUCCESS',
    ADD_TASK_REQUEST:    'ADD_TASK_REQUEST',
    REMOVE_TASK_REQUEST: 'REMOVE_TASK_REQUEST',
    EDIT_TASK_REQUEST:   'EDIT_TASK_REQUEST',
});
